spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  application:
    name: mediabase


logging.level:
  root: WARN
  com.example.mediabase.podcastsui: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000