spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  application:
    name: prftmgmt


logging.level:
  root: WARN
  com.example.prftmgmt.ticketsui: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000